### ISSUE TITLE
MATCH T-SQL keyword causes mssql extension to fail

### ISSUE THREAD

**Issue by rgward** [Microsoft/vscode-mssql#1092]
- MSSQL Extension Version:  1.3.1
- VSCode Version: 1.21.1
- OS Version: Windows 10 (I've seen reports it also happens on macOS)

Steps to Reproduce:

Open the following T-SQL script file and you get the following error "mssql: SQL Tools Service component could not start."

USE graphdemo
GO
-- Find Restaurants that John likes
SELECT Restaurant.name
FROM Person, likes, Restaurant
WHERE MATCH (Person-(likes)->Restaurant)
AND Person.name = 'John';
GO
-- Find Restaurants that John's friends like
--
SELECT Restaurant.name
FROM Person person1, Person person2, likes, friendOf, Restaurant
WHERE MATCH(person1-(friendOf)->person2-(likes)->Restaurant)
AND person1.name='John';
GO

**Comment by ChrisPatten** [comment]
Adding on to this:

* SQL Operations Studio Version: sqlops 0.26.7 (723c7cb, 2018-02-16T21:17:29.202Z)
* OS Version: Darwin x64 16.7.0
* Extensions: none

I run into this issue when there's `MATCH` or any `$` characters (like `$from_id`). I don't experience it when using `NODE` or `EDGE`.

Here's my `MATCH` query:

```
SELECT  si.Name AS [Site], 
        COUNT(DISTINCT sc.SchoolKey) AS [Schools], 
        COUNT(st.StudentKey) AS [Students],
        COUNT(st.StudentKey) * 1.0 / COUNT(DISTINCT sc.SchoolKey) AS [Students per School]
FROM graph.Sites si, graph.Schools sc, graph.Students st, graph.Enrollments en, graph.LocatedAt la
WHERE MATCH(st-(en)->sc-(la)->si)
GROUP BY si.Name
ORDER BY [Students per School] DESC

SELECT TOP (10)
        si.Name AS [Site],
        COUNT(st.StudentKey) * 1.0 / COUNT(DISTINCT se.SectionKey) AS [Students per Section]
FROM    graph.Sites si, 
        graph.Schools sc, 
        graph.Sections se, 
        graph.Students st, 
        graph.LocatedAt schoolLA,
        graph.LocatedAt sectionLA,
        graph.Enrollments enr
WHERE MATCH(st-(enr)->se-(sectionLA)->sc-(schoolLA)->si)
GROUP BY si.Name
ORDER BY [Students per Section] DESC
```

**Comment by MattIrv** [comment]
Stack trace:
```
   at Microsoft.SqlServer.Management.SqlParser.Parser.Internals.VersionedParserBase.Parse(Boolean isIncremental, String sql, SqlScript prevScript, ParseOptions options, ParseOptions& resultOptions)
   at Microsoft.SqlServer.Management.SqlParser.Parser.Parser.Parse(Boolean isIncremental, String sql, ParseResult prevResult, ParseOptions options, ParseOptions& resultOptions)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.<>c__DisplayClass60_0.<ParseAndBind>b__0() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 769
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 (at CustomOutputChannel.append (/Users/mairvine/code/sqlopsstudio/extensions/mssql/out/main.js:339:17))
```

**Comment by MattIrv** [comment]
This is fixed in SQL Tools Service now and will be included in our next release
