### ISSUE TITLE
Canceling out of password request dialog leaves node in broken state

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1302]
- MSSQL Extension Version: 1.7.0

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:

1. Save connection with SQL Auth and without saving password
2. Restart VS Code
3. Expand node - it prompts for password
4. Hit cancel (ESC)

Expected :

* Node is collapsed and can be expanded again
* Selecting refresh action will try to connect

Actual :

* Node is left expanded but without any children. Clicking on the node doesn't change the expanded state and no connection is prompted
* Selecting Refresh does nothing and these errors appears in console

```
[object Object]]System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.ObjectExplorerService.HandleRefreshRequest(RefreshParams refreshParams, RequestContext`1 context) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\ObjectExplorerService.cs:line 245

Error: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.SqlTools.ServiceLayer.ObjectExplorer.ObjectExplorerService.HandleRefreshRequest(RefreshParams refreshParams, RequestContext`1 context) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\ObjectExplorerService.cs:line 245
	at handleResponse (c:\Users\chgagnon\.vscode\extensions\ms-mssql.mssql-1.7.0\node_modules\vscode-jsonrpc\lib\main.js:436:48)
	at processMessageQueue (c:\Users\chgagnon\.vscode\extensions\ms-mssql.mssql-1.7.0\node_modules\vscode-jsonrpc\lib\main.js:263:17)
	at Immediate.setImmediate (c:\Users\chgagnon\.vscode\extensions\ms-mssql.mssql-1.7.0\node_modules\vscode-jsonrpc\lib\main.js:247:13)
	at runCallback (timers.js:694:18)
	at tryOnImmediate (timers.js:665:5)
	at processImmediate (timers.js:647:5)
```

**Comment by abist** [comment]
This is now fixed.
