### ISSUE TITLE
Contents not redrawn when switching between multiple results windows

### ISSUE THREAD

**Issue by kenvanhyning** [microsoft/vscode-mssql#1324]
Testing for September release on Windows x64 pkg.

Steps to Reproduce:

1.  Create new query and attach to server 1, type a simple query
2.  Execute query
3. Create another new query and attach to server 2, type another simple query
4. Execute second query

UI will have 2 results windows.  Results from #4 are visible on top of #2 

5. Click on the tab for #2 
6. UI displays: 
![image](https://user-images.githubusercontent.com/7833721/65553343-84e03100-dedb-11e9-8dde-8a49b35fcba6.png)

No results are ever redrawn.

Console in developer tools has this error:
mainThreadExtensionService.ts:65 SyntaxError: Unexpected token r in JSON at position 0
	at JSON.parse (<anonymous>)
	at MessageProxy.onReceive (c:\Users\kenvh\.vscode\extensions\ms-mssql.mssql-1.7.0\out\src\protocol.js:69:30)
	at constructor.self.protocol.onMessage.message.disposables.push.self.protocol.onMessage.val (c:\Users\kenvh\.vscode\extensions\ms-mssql.mssql-1.7.0\out\src\protocol.js:41:79)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at d.$onMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:611:836)
	at d._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:623:396)
	at d._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:623:88)
	at d._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:783)
	at d._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:605)
	at define.constructor._protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:618:791)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:579)
	at i.constructor.e.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:783:484)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at v.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:579)
	at x._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:17)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:116)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:207)
	at f.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:17)
	at define.constructor._register._socket.onData.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:183:372)
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:192:491)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by kburtram** [comment]
I also hit this issue.  Though I don't have a solid repro yet either.  Something with tab switching.

![image](https://user-images.githubusercontent.com/599935/65557241-68e28c80-dee7-11e9-822b-089c3b90fdd4.png)
