### ISSUE TITLE
ArgumentOutOfRangeException in SQL Tools Service

### ISSUE THREAD

**Issue by xsoheilalizadeh** [microsoft/vscode-mssql#1681]
Issue Type: <b>Bug</b>

## Exception
```
[Error - 2:17:16 PM] Request textDocument/definition failed.
  Message: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Babel.ParserGenerator.MinimalList`1.get_Item(Int32 index)
   at Babel.ParserGenerator.ModifiedMinimalList`1.get_Item(Int32 index)
   at Microsoft.SqlServer.Management.SqlParser.Parser.TokenManager.GetToken(Int32 tokenNumber)
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.Completion.ScriptDocumentInfo.GetPeekDefinitionTokens(ScriptParseInfo scriptParseInfo, Int32 startLine, Int32 startColumn) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\ScriptDocumentInfo.cs:line 158
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.GetDefinition(TextDocumentPosition textDocumentPosition, ScriptFile scriptFile, ConnectionInfo connInfo) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 1343
   at Microsoft.SqlTools.ServiceLayer.LanguageServices.LanguageService.HandleDefinitionRequest(TextDocumentPosition textDocumentPosition, RequestContext`1 requestContext) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\LanguageServices\LanguageService.cs:line 515
  Code: 0 
```

## SQL Script
```sql
select bus_order.PassengerName as bus_passanger,
    sale.PassengerName as sale_passanger
from BusOrder as bus_order
    JOIN [724SalesReportUTF8] sale on 1 = 1
where
    -- REPLACE(bus_order.PassengerName,' ','')  = REPLACE(sale.PassengerName,' ','')
    -- and 
    bus_order.Phone = sale.PhoneNumber
    --   and bus_order.Price = CAST(sale.CustomerPrice as bigint)
    and bus_order.DepartDate = sale.DepartureDate
    and bus_order.Status != 'Reserved'
    and bus_order.TicketNumber is null

-- UPDATE BusOrder
-- SET TicketNumber = CAST(sale.TicketNumber as bigint)
-- FROM BusOrder bus_order
--     JOIN [724SalesReportUTF8] sale on 1 = 1
-- where REPLACE(bus_order.PassengerName,' ','')  = REPLACE(sale.PassengerName,' ','')
--     and bus_order.Phone = sale.PhoneNumber
--     --   and bus_order.Price = CAST(sale.CustomerPrice as bigint)
--     and bus_order.DepartDate = sale.DepartureDate
--     and bus_order.Status != 'Reserved'
--     and bus_order.TicketNumber is null
```

Extension version: 1.9.0
VS Code version: Code - Insiders 1.46.0-insider (e88b8d32aa7233f6cb3665f6dae9fa78b1e8aafb, 2020-05-13T08:04:48.706Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (1.96GB free)|
|Process Argv|--folder-uri file:///c%3A/Code/alibaba/Distinguish|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by xsoheilalizadeh** [comment]
I think this issue should move to [microsoft/sqltoolsservice](https://github.com/microsoft/sqltoolsservice), am I right?
@abist

**Comment by abist** [comment]
@xsoheilalizadeh Yes, you're right that the issue is in [sqltoolsservice](https://github.com/microsoft/sqltoolsservice), but since it affects this extension, we can keep it open here as well.

**Comment by kburtram** [comment]
The sample script appears to run as expected on the current build—the query executes, but (as expected) returns server errors since the required tables don’t exist in my environment. Please let us know if you’re still experiencing this issue. Thanks again for reporting it!

![Image](https://github.com/user-attachments/assets/cc65d717-7f10-4a71-9319-2648546e4a71)
