### ISSUE TITLE
Can't connect to SQL Server from this extension

### ISSUE THREAD

**Issue by Nefcanto** [microsoft/vscode-mssql#16998]
- MSSQL Extension Version: v1.10.1
- VSCode Version:  
```
Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T16:45:26.313Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Linux x64 5.8.0-53-generic snap
```
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Install a fresh version of Visual Studio Code (version above)
2. Install the vscode-mssql extension (id => ms-mssql.mssql) (version above)
3. Try to connect to your first SQL Server instance

I get this error:

```
mssql: Failed to connect: Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
   at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
   at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost)
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired)
   at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass45_0.<TryGetConnection>b__1(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass30_0.<<OpenAsync>b__0>d.MoveNext() in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 314
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 550
ClientConnectionId:d645d51b-c885-4b7b-99c7-d5a2f8f41c9f
```

And the pinned issue didn't help me. Because I added `trustServerCertificate` to `mssql.connections` JSON and restart VS Code and again received this error.

**Comment by andreascian** [comment]
I got the same issue here with `mssql` v1.10.1 and

```
Version: 1.58.0-insider
Commit: 4c952751a88154ff4c375b1ca78293ab53a5792a
Date: 2021-07-06T21:30:49.113Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-77-generic snap
```

**Comment by mmunchandersen** [comment]
In my vscode 1.60.1, MSSQL Extension Version: v1.10.1 never finds a db driver
![2021-09-19_06-26-31](https://user-images.githubusercontent.com/3047487/133917120-b83b8a5a-8350-4999-867b-54cda4c5464e.png)
:

**Comment by JoeJGast** [comment]
I ran into the same issue as @Nefcanto on some of my servers.

One thing I noticed is that I was only getting this error on servers which required `Encrypt=true;` within the connection string when I connected with other tools.

For example, I can use the vscode extension to connect to a server which requires the following connection string `server='myserver';database='mydatabase';trusted_connection=true;`

however I cannot use the vscode extensions to connect to servers which require the following connection string
`server='myserver';database='mydatabase';trusted_connection=true;Encrypt=true;`

I had noticed that `mssql.connections` has a property called `encrypt` which defaults to false, however setting this to true did not help in my case.

Example:
``` javascript
{
      "mssql.connections": [
          {
              "server": "mpclkurdev4",
              "database": "GrantsDev",
              "authenticationType": "Integrated",
              "profileName": "",
              "password": "",
              "trustServerCertificate": true,
              "encrypt": true
          }
  ]
}
```

Using SQL Server version v1.13.0
VS Code version v1.62.3

**Comment by Benjin** [comment]
Are you still encountering this issue?  I'm going to close it now, but please re-open it if you're still hitting it.

**Comment by SuperNinja-4965** [comment]
Hi, i'm having this issue currently, I noticed i was also experiencing this issue with the Microsoft msodbcsql driver for linux. 
After many hours of debugging i noticed that msodbcsql was using opensslv3 and would not fallback to openssl -1.1 via the compat package i have installed on my system (Arch Linux)

I was able to fix msodbcsql by writing a shim used via LD_PRELOAD to force msodbcsql to use openssl-1.1 but i was just wondering if there was a way i could set this up for this extension. 
The SQL server is running old ssl codecs and this cannot change however opensslv3 does not support those codecs causing the issue
```
mssql: Connection error: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
```

Extension version: 1.35.0
VS Code version: 1.103.0

**Comment by kburtram** [comment]
> Hi, i'm having this issue currently, I noticed i was also experiencing this issue with the Microsoft msodbcsql driver for linux. After many hours of debugging i noticed that msodbcsql was using opensslv3 and would not fallback to openssl -1.1 via the compat package i have installed on my system (Arch Linux)
> 
> I was able to fix msodbcsql by writing a shim used via LD_PRELOAD to force msodbcsql to use openssl-1.1 but i was just wondering if there was a way i could set this up for this extension. The SQL server is running old ssl codecs and this cannot change however opensslv3 does not support those codecs causing the issue
> 
> ```
> mssql: Connection error: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
> ```
> 
> Extension version: 1.35.0 VS Code version: 1.103.0

@SuperNinja-4965 Thanks for sharing the details! The MSSQL VS Code extension uses the .NET Core SqlClient driver (via the bundled SQL Tools Service), so it doesn’t support swapping in alternate OpenSSL versions the way ODBC does.

If possible, the more reliable approach is to configure the SQL Server to work with the current SSL/TLS protocols supported by SqlClient. Could you share which version of SQL Server you’re connecting to in this environment? That’ll help us narrow down the compatibility issues.

**Comment by SuperNinja-4965** [comment]
Hi,
Just to clarify the ODBC driver doesn't support swapping the ssl library either, ive literally written a piece C that intercepts the requests to load the openssl driver from ODBC and give it the openssl1.1.

Unfortunately the server cant be reconfigured or have it's sql version upgraded - its used with some very legacy applications and so the ssl config it uses was depreciated from openssl v3.

Im happy to share the C code but i doubt its a long term solution.
Is there a way to be able to disable ssl on the extension?
