### ISSUE TITLE
mssql: SQL Tools Service component could not start.

### ISSUE THREAD

**Issue by Devtronyx** [microsoft/vscode-mssql#17012]
- MSSQL Extension Version: 1.10.1
- VSCode Version:1.58.2
- OS Version: macOS 12.0 Beta

Steps to Reproduce:

1. Open a file with .sql extension

The following error alerts appear:
The AzureResourceProvider server crashed 5 times in the last 3 minutes. The server will not be restarted.
mssql: SQL Tools Service component could not start.

In the AzureResourceProvider console I got:
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_ExternalException
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Runtime.InteropServices.SEHException..ctor()
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(System.Reflection.MetadataToken, System.Reflection.MetadataImport ByRef, System.Reflection.RuntimeModule, System.Reflection.MetadataToken, System.RuntimeType, Boolean, ListBuilder`1<System.Object> ByRef, System.RuntimeType ByRef, System.IRuntimeMethodInfo ByRef, Boolean ByRef, Boolean ByRef)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1<System.Object> ByRef, System.Reflection.RuntimeModule, Int32, System.RuntimeType, Boolean, ListBuilder`1<System.Object>)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeAssembly, System.RuntimeType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(System.Type, Boolean)
   at System.Attribute.GetCustomAttributes(System.Reflection.Assembly, System.Type, Boolean)
   at System.Attribute.GetCustomAttribute(System.Reflection.Assembly, System.Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.Assembly)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.get_ResourceManager()
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Runtime.InteropServices.SEHException..ctor()
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(System.Reflection.MetadataToken, System.Reflection.MetadataImport ByRef, System.Reflection.RuntimeModule, System.Reflection.MetadataToken, System.RuntimeType, Boolean, ListBuilder`1<System.Object> ByRef, System.RuntimeType ByRef, System.IRuntimeMethodInfo ByRef, Boolean ByRef, Boolean ByRef)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(System.Reflection.RuntimeModule, Int32, System.RuntimeType, Int32, Boolean)
   at System.Reflection.CustomAttribute.IsDefined(System.RuntimeType, System.RuntimeType, Boolean)
   at System.RuntimeType.IsDefined(System.Type, Boolean)
   at System.Enum.GetEnumInfo(System.RuntimeType, Boolean)
   at System.RuntimeType.IsEnumDefined(System.Object)
   at System.Enum.IsDefined(System.Type, System.Object)
   at System.Environment.GetFolderPath(SpecialFolder, SpecialFolderOption)
   at Microsoft.SqlTools.Hosting.Utility.CommandOptions..ctor(System.String[], System.String)
   at Microsoft.SqlTools.ResourceProvider.Program.Main(System.String[])
[Info  - 11:49:04 AM] Connection to server got closed. Server will restart.

And in the SQLToolsService:
Process terminated. Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_ExternalException
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Runtime.InteropServices.SEHException..ctor()
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(System.Reflection.MetadataToken, System.Reflection.MetadataImport ByRef, System.Reflection.RuntimeModule, System.Reflection.MetadataToken, System.RuntimeType, Boolean, ListBuilder`1<System.Object> ByRef, System.RuntimeType ByRef, System.IRuntimeMethodInfo ByRef, Boolean ByRef, Boolean ByRef)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1<System.Object> ByRef, System.Reflection.RuntimeModule, Int32, System.RuntimeType, Boolean, ListBuilder`1<System.Object>)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeAssembly, System.RuntimeType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(System.Type, Boolean)
   at System.Attribute.GetCustomAttributes(System.Reflection.Assembly, System.Type, Boolean)
   at System.Attribute.GetCustomAttribute(System.Reflection.Assembly, System.Type, Boolean)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Reflection.Assembly)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.get_ResourceManager()
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.Runtime.InteropServices.SEHException..ctor()
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(System.Reflection.MetadataToken, System.Reflection.MetadataImport ByRef, System.Reflection.RuntimeModule, System.Reflection.MetadataToken, System.RuntimeType, Boolean, ListBuilder`1<System.Object> ByRef, System.RuntimeType ByRef, System.IRuntimeMethodInfo ByRef, Boolean ByRef, Boolean ByRef)
   at System.Reflection.CustomAttribute.IsCustomAttributeDefined(System.Reflection.RuntimeModule, Int32, System.RuntimeType, Int32, Boolean)
   at System.Reflection.CustomAttribute.IsDefined(System.RuntimeType, System.RuntimeType, Boolean)
   at System.RuntimeType.IsDefined(System.Type, Boolean)
   at System.Enum.GetEnumInfo(System.RuntimeType, Boolean)
   at System.RuntimeType.IsEnumDefined(System.Object)
   at System.Enum.IsDefined(System.Type, System.Object)
   at System.Environment.GetFolderPath(SpecialFolder, SpecialFolderOption)
   at Microsoft.SqlTools.Hosting.Utility.CommandOptions..ctor(System.String[], System.String)
   at Microsoft.SqlTools.ServiceLayer.Utility.ServiceLayerCommandOptions..ctor(System.String[])
   at Microsoft.SqlTools.ServiceLayer.Program.Main(System.String[])
[Error - 11:49:04 AM] Connection to server got closed. Server will not be restarted.

**Comment by trevans** [comment]
Started getting the same notification after upgrading to macOS 12. SQLToolsService output:

Error:
  An assembly specified in the application dependencies manifest (MicrosoftSqlToolsServiceLayer.deps.json) was not found:
    package: 'runtimepack.Microsoft.NETCore.App.Runtime.osx-x64', version: '5.0.7'
    path: 'System.AppContext.dll'
[Error - 4:34:11 PM] Connection to server got closed. Server will not be restarted.

**Comment by kburtram** [comment]
Closing older issues without recent repo reports as part of backlog cleanup.  Please let us know if you're still impacted by this issue.
