### ISSUE TITLE
Settings file save error does not propagate to user

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/vscode-mssql#17501]
- MSSQL Extension Version: Latest
- VSCode Version: Latest
- OS Version: Windows 11

Steps to Reproduce:

1. Open Settings file and keep it edited, don't save it
2. Add a new connection

**Expected**: Error Message prompts the user that settings file couldn't be saved as connection is not added to OE.
**Actual**: No indication to user, neither error not connection being created.

Console logs capture the below error, but it is not propagated to vscode window:
```
stack trace: Error: Unable to write into user settings because the file has unsaved changes. Please save the user settings file first and then try again.
    at w.y (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:6124)
    at w.E (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:9526)
    at w.n (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:3153)
    at Object.factory (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:3053)
    at T.h (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:15888)
    at vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:15800
    at new Promise (<anonymous>)
    at T.queue (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:89:15742)
    at w.writeConfiguration (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:3022)
    at B.Hb (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:28740)
    at vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:17220
    at Array.map (<anonymous>)
    at B.updateValue (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2436:17208)
    at b.h (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1681:1433)
    at b.g (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1681:1270)
    at b.$updateConfigurationOption (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1681:781)
    at v.N (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:10803)
    at v.M (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:10521)
    at v.H (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:9614)
    at v.G (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:8752)
    at vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1690:7383
    at u.invoke (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at s.deliver (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at d.fire (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at o.fire (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:550:14605)
    at te.onmessage (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1927:1471)
```

Found the existing issue from discussion: https://github.com/microsoft/vscode-mssql/pull/17484#discussion_r1042517439

**Comment by kburtram** [comment]
This error is occurring within VS Code main process and isn't propagated to the extension.  Displaying this error should probably be handled by VS Code.  Closing as "out of scope".
