### ISSUE TITLE
Device Code authentication doesn't work (ADAL)

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/vscode-mssql#17559]
- MSSQL Extension Version: 1.17.1
- VSCode Version: Latest
- OS Version: Windows 11

Steps to Reproduce:

1. Enable Device Code authentication mode
2. Add a new account
3. After completing authentication, user is notified as below:

![image](https://user-images.githubusercontent.com/13396919/221653230-a70dd644-844e-4933-9add-aeba7bcc7668.png)
(should be VSCode-MSSQL)

Authentication also doesn't complete, as it fails with below error:

```
2023-02-27 10:39:41.814 [error] TypeError: this.stringLookup.getInteractionRequiredString is not a function
    at AzureDeviceCode.askUserForInteraction (c:\Users\~\.vscode\extensions\ms-mssql.mssql-1.17.1\node_modules\@microsoft\ads-adal-library\dist\engine\AzureAuth.js:367:69)
    at AzureDeviceCode.handleInteractionRequired (c:\Users\~\.vscode\extensions\ms-mssql.mssql-1.17.1\node_modules\@microsoft\ads-adal-library\dist\engine\AzureAuth.js:353:39)
    at AzureDeviceCode.getToken (c:\Users\~\.vscode\extensions\ms-mssql.mssql-1.17.1\node_modules\@microsoft\ads-adal-library\dist\engine\AzureAuth.js:188:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at AzureDeviceCode.getAccountSecurityToken (c:\Users\~\.vscode\extensions\ms-mssql.mssql-1.17.1\node_modules\@microsoft\ads-adal-library\dist\engine\AzureAuth.js:159:24)
```

**Comment by cheenamalhotra** [comment]
The underlying error seems to be:

```
mssql: ServerError: invalid_grant: 50005 : AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
```

This only occurs in VSCode-mssql extension when silently authenticating to Azure SQL resource with an account added via Device Code flow. Same user can acquire token for same resource in Azure Data Studio.

**Comment by cheenamalhotra** [comment]
Update: This issue is resolved when `Mssql: Enable SQL Authentication Provider` setting is enabled.
