### ISSUE TITLE
SqlTools Logs capture NRE in Table Designer service

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/vscode-mssql#17624]
- MSSQL Extension Version: Latest
- VSCode Version: Latest
- OS Version: Windows 11

Steps to Reproduce:

1. Open SqlTools.log for VSCode MSSQL extension
2. Below error is captured multiple times:

```
23-03-15 12:03:36.0629712 pid:10484 tid:12 sqltools Error: 0 : Unknown error System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.UpdateSettings(SqlToolsSettings newSettings, SqlToolsSettings oldSettings, EventContext eventContext) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 75
   at Microsoft.SqlTools.ServiceLayer.Workspace.WorkspaceService`1.<>c__DisplayClass40_0.<HandleDidChangeConfigurationNotification>b__0(ConfigChangeCallback t) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Workspace\WorkspaceService.cs:line 337
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)
   at Microsoft.SqlTools.ServiceLayer.Workspace.WorkspaceService`1.HandleDidChangeConfigurationNotification(DidChangeConfigurationParams`1 configChangeParams, EventContext eventContext) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Workspace\WorkspaceService.cs:line 336
```

**Comment by kburtram** [comment]
@aasimkhan30 could you please confirm whether this is still a problem?

**Comment by kburtram** [comment]
I couldn't repro this with the current builds.  After testing numerous extension features I didn't see any TableDesigner or NullReferenceException entries in the sqltoolsservice log.  Please let us know if you're still hitting this error.  Thanks!
