### ISSUE TITLE
V1.18.0 seems to break the extension

### ISSUE THREAD

**Issue by lewismazzei** [microsoft/vscode-mssql#17644]
- MSSQL Extension Version: V1.18.0
- VSCode Version: 1.76.2
- OS Version: 13.0

Steps to Reproduce:

1. MS SQL: Execute query
mssql: Error: Login failed. Retry using different credentials?
2. Retry:
mssql: Connection error : Login failed for user 'SA'.
and
mssql: Failed to connect: System.ArgumentNullException: Value cannot be null. (Parameter 'User ID')
   at Microsoft.Data.Common.ADP.CheckArgumentNull(Object value, String parameterName)
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.SetValue(String keyword, String value)
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.set_UserID(String value)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.CreateConnectionStringBuilder(ConnectionDetails connectionDetails) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1417
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.BuildConnectionString(ConnectionDetails connectionDetails) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1374
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 674

**Comment by kburtram** [comment]
@cheenamalhotra any ideas what could be happening here or how to investigate?

@lewismazzei have you tried deleting the connection and readding it?  Sometimes that can clear out "data state" about a particular connection.

**Comment by cheenamalhotra** [comment]
@lewismazzei 

Since it says `Login failed for user 'SA'` - I believe this is 'SqlLogin' authentication mode.
When you were prompted with "Login failed. Retry using different credentials?" what details did you fill in? Can you find your connection profile from settings.json and let us know what options are included?

**Comment by markusjohnsson** [comment]
I'm getting this too. Connecting to azure db using connection string. Firewall includes my ip. Exact connection string works from separate .net app. I'm on macOS 13.2.

**Comment by scharnyw** [comment]
Same here. I'm connecting to a SQL server database SaaS on Azure using connection string. On 1.18 I'm getting the error:

> mssql: Connection error : Login failed for user 'xxxx'.

No error logs in VS Code extension host, and in the MSSQL extension logs for that session it shows:

> [5:14:03 PM] Connecting to server "{serverEndpoint}" on document "{connectionString}".
> [5:14:06 PM] Connected to server "{serverEndpoint}" on document "{connectionString}". Server information: bla bla bla

Yet I'm seeing the error on UI. After downgrading to 1.17.1 everything works again.

**Comment by markusjohnsson** [comment]
Still unusable here.

**Comment by Henningsson** [comment]
unusable here on osx

**Comment by cheenamalhotra** [comment]
Issue has been addressed and verified - fix will be included in upcoming extension release - v1.20
