### ISSUE TITLE
Query results not displayed

### ISSUE THREAD

**Issue by kisantia** [microsoft/vscode-mssql#17838]
- MSSQL Extension Version: 1.22.0 (RC)
- VSCode Version: 1.83.1
- OS Version: macOS 13.6.1

actual:
![runQuery](https://github.com/microsoft/vscode-mssql/assets/31145923/ac1c790c-ff1f-4f3e-ab7a-6464fb6bc870)

expected (version 1.21.0)
![expectedRunQuery](https://github.com/microsoft/vscode-mssql/assets/31145923/f955e098-d709-449b-aec7-1e4efd5aa5a1)

**Comment by Charles-Gagnon** [comment]
Also seeing this, couple errors from the logs : 

```
Error: Unable to read file 'c:\Users\chgagnon\.vscode\extensions\ms-mssql.mssql-1.22.0\out\src\views\htmlcontent\src\js\lib\rxjs\operators.js' (Error: Unable to resolve nonexistent file 'c:\Users\chgagnon\.vscode\extensions\ms-mssql.mssql-1.22.0\out\src\views\htmlcontent\src\js\lib\rxjs\operators.js')
    at r.F (fileService.ts:621:10)
    at r.D (fileService.ts:606:15)
    at async p (resourceLoading.ts:68:18)
    at async n.wb (webviewElement.ts:733:19)
file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/rxjs/operators.js:1     Failed to load resource: the server responded with a status of 404 ()
index.html?id=8633ef4f-a432-4edc-93fa-2da8d2d391da&origin=e8099826-7fd8-46fa-8909-6169ec55c8cc&swVersion=4&extensionId=ms-mssql.mssql&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app:2 (SystemJS) XHR error (404) loading https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/rxjs/operators.js
	Error: XHR error (404) loading https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/rxjs/operators.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/zone.js/dist/zone.js:698:29)
	    at ZoneDelegate.invokeTask (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/zone.js/dist/zone.js:265:35)
	    at Zone.runTask (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/zone.js/dist/zone.js:154:47)
	    at ZoneTask.invoke (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/zone.js/dist/zone.js:335:33)
	Error loading https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/rxjs/operators.js as "rxjs/operators" from https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/.vscode/extensions/ms-mssql.mssql-1.22.0/out/src/views/htmlcontent/src/js/lib/@angular/core/bundles/core.umd.js
```

**Comment by kisantia** [comment]
verified this is fixed in the latest RC build
