### ISSUE TITLE
'Webview is disposed' exception using Connection Dialog

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18006]
Steps to Reproduce:

1. Testing Connection Dialog.  No consistent repro steps yet.

Expected: No unhandled exceptions

Actual: Webview disposed exception.  Connection then proceeds to fail.

![image](https://github.com/user-attachments/assets/4a811e1a-188c-4b59-ae91-b30ceb2a8ffc)

Here's the exception text
```
console.ts:137 [Extension Host] stack trace: Error: Webview is disposed
	at I.c (c:\Users\karlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:53097)
	at get webview (c:\Users\karlb\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:52250)
	at ConnectionDialogWebViewController._getWebview (c:\Users\karlb\.vscode\extensions\ms-mssql.mssql-1.24.0\out\src\controllers\reactWebviewController.js:45:28)
	at ConnectionDialogWebViewController.postMessage (c:\Users\karlb\.vscode\extensions\ms-mssql.mssql-1.24.0\out\src\controllers\reactWebviewBaseController.js:185:14)
	at ConnectionDialogWebViewController.postNotification (c:\Users\karlb\.vscode\extensions\ms-mssql.mssql-1.24.0\out\src\controllers\reactWebviewBaseController.js:178:14)
	at set state (c:\Users\karlb\.vscode\extensions\ms-mssql.mssql-1.24.0\out\src\controllers\reactWebviewBaseController.js:164:14)
	at ConnectionDialogWebViewController.<anonymous> (c:\Users\karlb\.vscode\extensions\ms-mssql.mssql-1.24.0\out\src\controllers\reactWebviewBaseController.js:106:28)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\karlb\.vscode\extensions\ms-mssql.mssql-1.24.0\out\src\controllers\reactWebviewBaseController.js:9:58)
```

**Comment by kburtram** [comment]
@aasimkhan30 not sure if the exception text is enough to determine what's going on here.  Otherwise, we can close and wait for better repro steps.  Thanks!

**Comment by aasimkhan30** [comment]
This is fixed by this line: https://github.com/microsoft/vscode-mssql/blob/aa522540d89456d8598a33ef0942d52a0ae292db/src/controllers/reactWebviewBaseController.ts#L244
