### ISSUE TITLE
Two result grids displayed for a single result set

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18477]
Steps to Reproduce:

1. Run a simple query

```SQL
SELECT TOP (1000) [OrderID]
      ,[CustomerID]
      ,[SalespersonPersonID]
      ,[PickedByPersonID]
      ,[ContactPersonID]
      ,[BackorderOrderID]
      ,[OrderDate]
      ,[ExpectedDeliveryDate]
      ,[CustomerPurchaseOrderNumber]
      ,[IsUndersupplyBackordered]
      ,[DeliveryInstructions]
      ,[InternalComments]
      ,[Comments]
      ,[PickingCompletedWhen]
      ,[LastEditedBy]
      ,[LastEditedWhen]
  FROM [WideWorldImporters].[Sales].[Orders]
```

2. Not sure it mattered, but I was trying to scroll the grid while it was populating, maybe that triggered some event.

Expected: 1 results set

Actual: 2 results sets

Note: obviously this doesn't repro consistently, so we should try to understand what could cause this, like a timing race conditions, etc.  Or add more logging to diagnosis it better next time.

![Image](https://github.com/user-attachments/assets/f8ddbdc0-6cc5-42fa-9292-39ea6de28bf1)

Here are some exceptions stacks from the log

```
react-jsx-runtime.development.js:87 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `QueryResultPane`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at QueryResultPane (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/queryResult.js:16539:19)
    at div
    at div
    at QueryResult (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/queryResult.js:16985:19)
    at QueryResultStateProvider (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/queryResult.js:12671:3)
    at div
    at TextDirectionProvider (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/chunk-Z6VBRQCO.js:27380:3)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/chunk-Z6VBRQCO.js:36777:17
    at VscodeWebviewProvider (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/chunk-Z6VBRQCO.js:58061:3)
printWarning @ react-jsx-runtime.development.js:87
Show 1 more frame
Show less
react-dom.development.js:86 Warning: Cannot update a component (`ResultGrid`) while rendering a different component (`QueryResultPane`). To locate the bad setState() call inside `QueryResultPane`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at QueryResultPane (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/queryResult.js:16539:19)
    at div
    at div
    at QueryResult (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/queryResult.js:16985:19)
    at QueryResultStateProvider (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/queryResult.js:12671:3)
    at div
    at TextDirectionProvider (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/chunk-Z6VBRQCO.js:27380:3)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/chunk-Z6VBRQCO.js:36777:17
    at VscodeWebviewProvider (https://file+.vscode-resource.vscode-cdn.net/c%3A/Repos/vscode-mssql/out/src/reactviews/assets/chunk-Z6VBRQCO.js:58061:3)
```

**Comment by cssuh** [comment]
Closing since this should be fixed here: https://github.com/microsoft/vscode-mssql/pull/18895
