### ISSUE TITLE
SELECT from WideWorldImporters.Sales.Customers fails

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#548]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8
- OS Version: OpenSuse 13.2

![vscode](https://cloud.githubusercontent.com/assets/599935/21258186/b1ed0e62-c330-11e6-9536-54b4d2e9d555.png)

Steps to Reproduce:

1. Install WWI DB
2. Run following query "SELECT * FROM Sales.Customers"

Expected: Results show correctly

Actual: Results grid show with all the data row values missing.  The following exception is thrown.

$exception
{System.FormatException: Input string was not in a correct format.
   at System.DateTimeFormat.FormatCustomized(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi, TimeSpan offset)
   at System.DateTimeFormat.Format(DateTime dateTime, String format, DateTimeFormatInfo dtfi)
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.DataStorage.ServiceBufferFileStreamReader.<>c__DisplayClass16_0.<ReadDateTime>b__1(DateTime time) in /xplat/sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/DataStorage/ServiceBufferFileStreamReader.cs:line 281
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.DataStorage.ServiceBufferFileStreamReader.ReadCellHelper[T](Int64 offset, Func`2 convertFunc, Func`2 isNullFunc, Func`2 toStringFunc) in /xplat/sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/DataStorage/ServiceBufferFileStreamReader.cs:line 457
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.DataStorage.ServiceBufferFileStreamReader.ReadDateTime(Int64 offset) in /xplat/sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/DataStorage/ServiceBufferFileStreamReader.cs:line 265
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.DataStorage.ServiceBufferFileStreamReader.ReadRow(Int64 fileOffset, IEnumerable`1 columns) in /xplat/sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/DataStorage/ServiceBufferFileStreamReader.cs:line 138
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.ResultSet.<>c__DisplayClass43_0.<GetSubset>b__2(Int64 rowOffset) in /xplat/sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/ResultSet.cs:line 227
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.ResultSet.<>c__DisplayClass43_1.<GetSubset>b__0() in /xplat/sqltoolsservice/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/ResultSet.cs:line 227
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)}

**Comment by benrr101** [comment]
Will look into this right now.

**Comment by benrr101** [comment]
Serious (not workaround) fix is out for review Microsoft/sqltoolsservice#196. The fix also addresses a display issue for `DATE` columns.

**Comment by kburtram** [comment]
The DateTime precision change that introduced this regression has been rolled-back and ported to master for Preview 2 release.
