### ISSUE TITLE
Query execution hangs on 'Executing query...' and can not be cancelled.

### ISSUE THREAD

**Issue by Orphu7** [Microsoft/vscode-mssql#813]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.11.1
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Create a connection profile
2. Connect to the sql server (tried with several)
3. try to execute query (select * from sys.tables;)
4. The results dialog now displays "Executing query..." with the spinning wheel, but nothing happens.

Remarks:
- I can list the databases on the server and Intellisense works, so the connection seems ok.
- I had to install the sqltoolsservice manually (microsoft.sqltools.servicelayer-win-x64-netcoreapp1.0), because that installation failed behind a company proxy server.
- Cancelling the query does not work.

[edit] update:
Looking at the console in the developer tools while executing i see these errors:
```
address:"40.77.226.250"
code:"ETIMEDOUT"
errno:"ETIMEDOUT"
port:443
```
and
```
shell.ts:475Illegal argument, contents must be defined: Error: Illegal argument, contents must be defined
    at new e (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:232521)
    at asHover (C:\Users\rtbo\.vscode\extensions\ms-mssql.mssql-0.3.0\node_modules\vscode-languageclient\lib\protocolConverter.js:71:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:475
```

So apparantly it's related to why i'm not able to install the sqltools automatically. Still, shouldn't it be useable without an internet connection?

**Comment by Orphu7** [comment]
Installing the latest release(v0.3.0 alpha 22) from vsix fixed the problem for me.
https://github.com/Microsoft/vscode-mssql/releases

Possibly related to this:
https://github.com/Microsoft/vscode-mssql/issues/805
